table! {
    use diesel::sql_types::*;

    /// Representation of the `keys` table.
    ///
    /// (Automatically generated by Diesel.)
    keys (id) {
        /// The `id` column of the `keys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `primary` column of the `keys` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        primary -> Uuid,
        /// The `secondary` column of the `keys` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        secondary -> Uuid,
        /// The `created_at` column of the `keys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `updated_at` column of the `keys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamp,
    }
}
